[package]
name = "buddy_sys_test"
version = "0.1.0"
authors = ["lincyaw <814750204@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
buddy_system_allocator = "0.3.9"